version: '3.8'

services:
  configsvr1:
    image: mongo:latest
    container_name: configsvr1
    command: mongod --replSet configReplSet --configsvr --port 27019
    networks:
      - mongo-cluster
    ports:
      - 27019:27019

  configsvr2:
    image: mongo:latest
    container_name: configsvr2
    command: mongod --replSet configReplSet --configsvr --port 27019
    networks:
      - mongo-cluster
    ports:
      - 27020:27019

  shard1-node1:
    image: mongo:latest
    container_name: shard1-node1
    command: mongod --replSet shard1ReplSet --shardsvr --port 27018
    networks:
      - mongo-cluster
    ports:
      - 27021:27018

  shard1-node2:
    image: mongo:latest
    container_name: shard1-node2
    command: mongod --replSet shard1ReplSet --shardsvr --port 27018
    networks:
      - mongo-cluster
    ports:
      - 27022:27018

  shard2-node3:
    image: mongo:latest
    container_name: shard2-node3
    command: mongod --replSet shard2ReplSet --shardsvr --port 27018
    networks:
      - mongo-cluster
    ports:
      - 27023:27018

  mongos:
    image: mongo:latest
    container_name: mongos
    command: mongos --configdb configReplSet/configsvr1:27019,configsvr2:27019,configsvr3:27019
    networks:
      - mongo-cluster
    ports:
      - 27017:27017

networks:
  mongo-cluster:
    external: true
