version: '3.8'

services:
  configsvr1:
    image: mongo:latest
    container_name: configsvr1
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27019"]
    ports:
      - 27019:27019
    networks:
      - mongo-cluster
    volumes:
      - configdb1:/data/db

  shard1-node1:
    image: mongo:latest
    container_name: shard1-node1
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--port", "27018"]
    ports:
      - 27018:27018
    networks:
      - mongo-cluster
    volumes:
      - shard1node1:/data/db

  mongos:
    image: mongo:latest
    container_name: mongos
    command: ["mongos", "--configdb", "configReplSet/configsvr1:27019,configsvr2:27019,configsvr3:27019"]
    ports:
      - 27020:27020
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    external: true

volumes:
  configdb1:
  shard1node1:
